
# basic training
no_cuda : False
device_id : [0]

# experiment name (also name of the saving directory)
# model and log directory : {ROOT}/experiment/{exp_name}/
exp_name : "panda_orb_self_supervised" 

# Data
urdf_robot_name : "panda"
train_ds_names : "dream/real/panda-orb"
val_ds_names : None
image_size : 256.0

# Model
backbone_name : "resnet50"
rootnet_backbone_name : "hrnet32"
rootnet_image_size : 256.0
other_image_size : 256.0
use_rpmg: False

# Optimizer
lr : 1e-7
weight_decay : 0.
use_schedule : False
schedule_type : "exponential"
n_epochs_warmup : 0
start_decay : 20
end_decay: 300
final_decay : 0.01
exponent : 0.78

# Training
batch_size : 32
epoch_size : 104950
n_epochs : 700
n_dataloader_workers : 6
save_epoch_interval : None
clip_gradient : 10.0

# Method
use_direct_reg_branch : True
n_iter : 4
pose_loss_func : "mse"
rot_loss_func : "mse"
trans_loss_func : "l2norm"
depth_loss_func : "l1"
uv_loss_func : "l2norm"
kp2d_loss_func : "l2norm"
kp3d_loss_func : "l2norm"
pose_loss_weight : 1.0
rot_loss_weight : 1.0
trans_loss_weight : 1.0
depth_loss_weight : 1.0
uv_loss_weight : 0.0
kp2d_loss_weight : 10.0
kp3d_loss_weight : 10.0
reg_joint_map : False
joint_conv_dim : [256,256,256]
joint_individual_weights : None
use_joint_valid_mask : True


use_integral_3d_branch : False
use_limb_loss : False
limb_loss_func : "l1"
limb_loss_weight : 1.0
use_uvd_3d_loss : False
integral_3d_loss_func : "l2norm"
integral_3d_loss_weight : 1.0
use_xyz_3d_loss : True
integral_xyz_3d_loss_func : "l2norm"
integral_xyz_3d_loss_weight : 1.0
bbox_3d_shape :
  - 1300
  - 1300
  - 1300

reference_keypoint_id : 3   # 0:base 
fix_truncation : False

use_pretrained_direct_reg_weights: False
pretrained_direct_reg_weights_path: None

use_pretrained_integral : False
pretrained_integral_weights_path: None


# rootnet (+ integral/regression)
use_rootnet: False
resample : False
rootnet_depth_loss_weight : 1.0
depth_loss_func : "l1"
use_rootnet_xy_branch : False
xy_loss_func : "mse"
pretrained_rootnet: None
use_origin_bbox : False
use_extended_bbox : True

use_rootnet_with_regression_uv : False
use_rootnet_with_reg_int_shared_backbone : True
use_rootnet_with_reg_with_int_separate_backbone : False

use_sim2real : True
use_view : False
pretrained_weight_on_synth : "panda_synth_pretrain/ckpt/curr_best_auc(add)_orb_model.pk"

mask_loss_weight : 0.0
iou_loss_weight : 1.0
scale_loss_weight : 0.0
align_3d_loss_weight : 1.0

# Resume
resume_run : False
resume_experiment_name : "resume_name"
